name: andi-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipython
  - pip
  - pylint
  - numpy=1.19
  - scikit-learn=0.23.2
  - pandas=1.1.0
  - tqdm
  - keras=2.4.3
  - tensorflow-gpu=2.2.0
  - matplotlib=3.3.0
  - docopt
  - schema
  - pip:
    - fbm==0.3.0
    - andi-datasets==0.0.3
